version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - data_os_network

  dremio:
    image: dremio/dremio-oss:25.0.0
    ports:
      - "9047:9047"
      - "31010:31010"
      - "45678:45678"
      - "32010:32010"
    depends_on:
      - minio
    networks:
      - data_os_network

volumes:
  minio-data:

networks:
  data_os_network:
    driver: bridge
